# Linting configuration for golangci-lint
version: "2"
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - godot
    - gosec
    - revive
    - gocyclo
    - dupl
    - unparam
    - unconvert
    - prealloc
    - exportloopref
    - nolintlint
    - whitespace
  disable:
    - typecheck # disabled due to generics issues

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
