package gen

// Code generated by avro/gen. DO NOT EDIT.

// Expense is a generated struct.
type Expense struct {
	ExpenseID   string  `avro:"expense_id" json:"expense_id"`
	UserID      string  `avro:"user_id" json:"user_id"`
	Category    string  `avro:"category" json:"category"`
	Amount      float64 `avro:"amount" json:"amount"`
	Currency    string  `avro:"currency" json:"currency"`
	Timestamp   int64   `avro:"timestamp" json:"timestamp"`
	Description *string `avro:"description" json:"description"`
	Receipt     *string `avro:"receipt" json:"receipt"`
}
