package gen

// Code generated by avro/gen. DO NOT EDIT.

// OrderItem is a generated struct.
type OrderItem struct {
	ProductID   string  `avro:"product_id" json:"product_id"`
	ProductName string  `avro:"product_name" json:"product_name"`
	Quantity    int     `avro:"quantity" json:"quantity"`
	Price       float64 `avro:"price" json:"price"`
}

// Order is a generated struct.
type Order struct {
	OrderID         string      `avro:"order_id" json:"order_id"`
	CustomerID      string      `avro:"customer_id" json:"customer_id"`
	OrderDate       string      `avro:"order_date" json:"order_date"`
	Items           []OrderItem `avro:"items" json:"items"`
	ShippingAddress string      `avro:"shipping_address" json:"shipping_address"`
	PaymentMethod   string      `avro:"payment_method" json:"payment_method"`
}
