package gen

// Code generated by avro/gen. DO NOT EDIT.

// Payment is a generated struct.
type Payment struct {
	TransactionID string  `avro:"transaction_id" json:"transaction_id"`
	UserID        string  `avro:"user_id" json:"user_id"`
	Amount        float64 `avro:"amount" json:"amount"`
	Currency      string  `avro:"currency" json:"currency"`
	PaymentMethod string  `avro:"payment_method" json:"payment_method"`
	Timestamp     int64   `avro:"timestamp" json:"timestamp"`
	Status        string  `avro:"status" json:"status"`
}
