package gen

// Code generated by avro/gen. DO NOT EDIT.

import (
	"time"
)

// Payer is a generated struct.
type Payer struct {
	PayerID   string `avro:"payer_id" json:"payer_id"`
	PayerName string `avro:"payer_name" json:"payer_name"`
}

// Payee is a generated struct.
type Payee struct {
	PayeeID   string `avro:"payee_id" json:"payee_id"`
	PayeeName string `avro:"payee_name" json:"payee_name"`
}

// PaymentTransaction is a generated struct.
type PaymentTransaction struct {
	TransactionID string    `avro:"transaction_id" json:"transaction_id"`
	Timestamp     time.Time `avro:"timestamp" json:"timestamp"`
	Payer         Payer     `avro:"payer" json:"payer"`
	Payee         Payee     `avro:"payee" json:"payee"`
	Amount        float64   `avro:"amount" json:"amount"`
	Currency      string    `avro:"currency" json:"currency"`
	Status        string    `avro:"status" json:"status"`
}
