name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Event-Stream
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Application
        run: docker-compose up -d
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run tests
        run: make test    
      - name: check logs
        run: docker compose logs -t -f event-stream
