name: Tests

on:
  pull_request:
    branches: [ master ]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  test:
    name: event-shark
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Application
        run: docker compose up -d
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Run tests
        run: make test
      - name: Extract test results from container
        run: |
          docker cp eventstream:/app/test-report.json ./test-report.json
          ls -la ./test-report.json  # Verify file was extracted
      - name: Generate Test Report
        uses: dipjyotimetia/gotest-report@main
        with:
          test-json-file: test-output.json
          output-file: test-report.md
          comment-pr: true  
      - name: Compose down
        run: docker compose down --rmi all
