name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: event-shark
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Application
        run: docker-compose up -d
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Run tests
        run: make test
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/performance/tests/perf.js  
      - name: Compose down
        run: docker-compose down --rmi all
      - name: check logs
        run: docker compose logs -t -f event-shark
