name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Event-Stream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20' 
      - name: Setup Application
        run: docker-compose up -d
      - name: Integration Test
        run: |
          curl --location 'http://localhost:9050/expense' \
          --header 'Content-Type: application/json' \
          --data '{
              "expense_id": "1234",
              "user_id": "1234",
              "category": "1234",
              "amount": 12,
              "currency": "AUD",
              "timestamp": 1621786448000,
              "description": "Test new",
              "receipt": "new"
          }'
      - name: check logs
        run: docker compose logs -t -f event-stream
